spring:
  application:
    name: biblioteca-digital

  # Habilitamos los hilos virtuales para I/O no bloqueante
  threads:
    virtual:
      enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5432/biblioteca
    username: root
    password: rootpassword
    driver-class-name: org.postgresql.Driver

    # Optimizacion estricta de RAM
    hikari:
      maximum-pool-size: 5      # Solo permitimos 5 conexiones simultaneas
      minimum-idle: 2           # Mantiene 2 conexiones dormidas listas para usarse
      idle-timeout: 300000      # Cierra conexiones inactivas rapido para liberar memoria
      max-lifetime: 1200000     # Recicla conexiones cada 20 mins para evitar fugas de memoria

  # CONFIGURACION DE JPA / HIBERNATE
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_batch_fetch_size: 30

# CONFIGURACION DEL SERVIDOR WEB
server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

# CONFIGURACION DE LA API DE GOOGLE BOOKS
google:
  books:
    api-key: ${GOOGLE_BOOKS_API_KEY}

# CONFIGURACION SEGURIDAD JWT
jwt:
  secret: ${JWT_SECRET}

# CONFIGURACIÓN DE CLOUDINARY
cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}